In [57]:
# import libraries
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [58]:
#load the dataset 
df = pd.read_csv('/content/drive/MyDrive/hamoye/fuel_ferc1.csv')
df.head()

                record_id  ...  fuel_cost_per_mmbtu
0   f1_fuel_1994_12_1_0_7  ...                1.121
1  f1_fuel_1994_12_1_0_10  ...                1.120
2   f1_fuel_1994_12_2_0_1  ...                1.650
3   f1_fuel_1994_12_2_0_7  ...                1.970
4  f1_fuel_1994_12_2_0_10  ...                2.570

[5 rows x 11 columns]

In [59]:
reportt=df[['report_year','fuel_cost_per_unit_delivered', ]]
reporttt =reportt.groupby(['report_year'],as_index=False).mean()
reporttt=reporttt.sort_values(['fuel_cost_per_unit_delivered'], ascending=False)
reporttt

    report_year  fuel_cost_per_unit_delivered
3          1997                  11140.197239
2          1996                   9196.705948
6          2000                    985.362877
15         2009                    652.694163
24         2018                    499.269966
21         2015                    326.535511
4          1998                    287.154420
20         2014                    192.737183
19         2013                    172.307591
10         2004                    139.524275
22         2016                    103.901761
16         2010                     91.862105
0          1994                     63.636060
18         2012                     60.994502
7          2001                     60.050396
17         2011                     59.774667
14         2008                     58.588197
9          2003                     55.663493
8          2002                     47.594361
23         2017                     46.196861
13         2007                     43.325023
11         2005                     41.438184
12         2006                     38.657484
1          1995                     32.735269
5          1999                     25.551627

In [60]:
df.corr()

                              utility_id_ferc1  ...  fuel_cost_per_mmbtu
utility_id_ferc1                      1.000000  ...             0.006122
report_year                           0.093323  ...             0.010261
fuel_qty_burned                      -0.057447  ...            -0.001896
fuel_mmbtu_per_unit                  -0.066946  ...            -0.005884
fuel_cost_per_unit_burned            -0.037863  ...            -0.000437
fuel_cost_per_unit_delivered         -0.016414  ...            -0.000109
fuel_cost_per_mmbtu                   0.006122  ...             1.000000

[7 rows x 7 columns]

In [61]:
df.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [62]:
#writing a function for missing data, data types and unique elements
def missing_data(df):
    dtypes = df.dtypes
    nuniq = df.T.apply(lambda x: x.nunique(), axis=1)
    total = df.isnull().sum().sort_values(ascending = False)
    percent = (df.isnull().sum()/df.isnull().count()*100).sort_values(ascending = False)
    quality = pd.concat([total, percent, nuniq, dtypes], axis=1, keys=['Total', 'Percent','Nunique', 'Dtype'])
    display(quality)

In [63]:
missing_data(df)

                              Total   Percent  Nunique    Dtype
fuel_unit                       180  0.609694        9   object
fuel_cost_per_mmbtu               0  0.000000    12605  float64
fuel_cost_per_unit_delivered      0  0.000000    16675  float64
fuel_cost_per_unit_burned         0  0.000000    19416  float64
fuel_mmbtu_per_unit               0  0.000000    11227  float64
fuel_qty_burned                   0  0.000000    26432  float64
fuel_type_code_pudl               0  0.000000        6   object
plant_name_ferc1                  0  0.000000     2315   object
report_year                       0  0.000000       25    int64
utility_id_ferc1                  0  0.000000      185    int64
record_id                         0  0.000000    29523   object

In [64]:
import statistics

In [65]:
skeww = df["fuel_qty_burned"].skew()

In [66]:
print(skeww)

15.851495469109503

In [67]:
kurtt = df["fuel_qty_burned"].kurt()

In [68]:
print(kurtt)

651.3694501337732

In [69]:
stdd = df["fuel_mmbtu_per_unit"].std()

In [70]:
per = df["fuel_mmbtu_per_unit"].quantile([0.75])

In [71]:
print(stdd)

10.600220307806886

In [72]:
print(per)

0.75    17.006
Name: fuel_mmbtu_per_unit, dtype: float64

In [73]:
fuel_code=df[['fuel_type_code_pudl','fuel_cost_per_unit_burned', ]]
fuel_codee = fuel_code.groupby(['fuel_type_code_pudl'],as_index=False).mean()
fuel_codee=fuel_codee.sort_values(['fuel_cost_per_unit_burned'], ascending=False)
fuel_codee

  fuel_type_code_pudl  fuel_cost_per_unit_burned
2             nuclear                4955.157002
3                 oil                 168.877086
0                coal                  67.421830
5               waste                  19.518122
4               other                  18.253856
1                 gas                  13.659397

In [74]:
coall = df[(df['fuel_type_code_pudl'] == 'coal')]
coall.sample(10)

                      record_id  ...  fuel_cost_per_mmbtu
20776    f1_fuel_2011_12_70_0_4  ...                1.937
23616   f1_fuel_2013_12_146_0_1  ...                4.327
24553    f1_fuel_2014_12_99_0_2  ...                3.887
12783   f1_fuel_2004_12_281_1_7  ...                1.210
16114    f1_fuel_2007_12_49_0_7  ...                1.584
12214    f1_fuel_2004_12_57_2_1  ...                1.919
5785   f1_fuel_1999_12_195_3_10  ...                1.110
12111    f1_fuel_2004_12_45_0_7  ...                2.167
13958   f1_fuel_2005_12_160_0_1  ...                2.440
14044  f1_fuel_2005_12_195_3_10  ...                1.138

[10 rows x 11 columns]